library(mlr)
library(parallel)
library(reshape2)
library("parallelMap") 
library(latex2exp)
rm(list = ls())
# TODO: move to separate bbp data
# source('../neuro-intermorpho/R/bbp-data.R')
source('r/bring-in-data.R')
source('r/classify.R')
source('r/sample.R')
source('r/mlr.r')
source('r/read-data.r')
source('r/classify-data.r')
source('r/mlr-filters.r')
source('r/mlearn.r')
source('r/neuro.r')
source('r/features.R')
source('r/binary.R')
source('r/assess-frontend.r')
